// Export helpers for the current canvas: PNG / JPG / PDF raster output
// plus a LaTeX-flavoured export that writes the base image as PNG and
// emits a .tex overlay placing text and counter annotations as tikz
// nodes. The LaTeX path is the whole reason this file exists separately
// from a generic stage-to-dataURL call.

import Konva from 'konva'
import { jsPDF } from 'jspdf'
import type { ProjectState } from './exportTypes'

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function stageToDataURL(
  stage: Konva.Stage,
  canvasWidth: number,
  canvasHeight: number,
  mimeType: string,
  quality?: number,
  pixelRatio = 2,
): string {
  return stage.toDataURL({
    x: 0,
    y: 0,
    width: canvasWidth,
    height: canvasHeight,
    pixelRatio,
    mimeType,
    quality,
  })
}

export function exportPNG(stage: Konva.Stage, canvasWidth: number, canvasHeight: number, name: string, pixelRatio = 2) {
  const dataURL = stageToDataURL(stage, canvasWidth, canvasHeight, 'image/png', undefined, pixelRatio)
  const link = document.createElement('a')
  link.href = dataURL
  link.download = `${name}.png`
  link.click()
}

export function exportJPG(stage: Konva.Stage, canvasWidth: number, canvasHeight: number, name: string, pixelRatio = 2, quality = 0.92) {
  const dataURL = stageToDataURL(stage, canvasWidth, canvasHeight, 'image/jpeg', quality, pixelRatio)
  const link = document.createElement('a')
  link.href = dataURL
  link.download = `${name}.jpg`
  link.click()
}

export function exportPDF(
  stage: Konva.Stage, canvasWidth: number, canvasHeight: number, name: string,
  paperSize: 'canvas' | 'a4' | 'letter' = 'canvas',
) {
  const pixelRatio = paperSize === 'canvas' ? 2 : 3
  const dataURL = stageToDataURL(stage, canvasWidth, canvasHeight, 'image/png', undefined, pixelRatio)
  const orientation = canvasWidth >= canvasHeight ? 'landscape' : 'portrait'

  if (paperSize === 'canvas') {
    const pdf = new jsPDF({ orientation, unit: 'px', format: [canvasWidth, canvasHeight] })
    pdf.addImage(dataURL, 'PNG', 0, 0, canvasWidth, canvasHeight)
    pdf.save(`${name}.pdf`)
  } else {
    const format = paperSize === 'a4' ? 'a4' : 'letter'
    const pdf = new jsPDF({ orientation, unit: 'mm', format })
    const pageW = pdf.internal.pageSize.getWidth()
    const pageH = pdf.internal.pageSize.getHeight()
    const margin = 10
    const availW = pageW - margin * 2
    const availH = pageH - margin * 2
    const scale = Math.min(availW / canvasWidth, availH / canvasHeight)
    const imgW = canvasWidth * scale
    const imgH = canvasHeight * scale
    const x = (pageW - imgW) / 2
    const y = (pageH - imgH) / 2
    pdf.addImage(dataURL, 'PNG', x, y, imgW, imgH)
    pdf.save(`${name}.pdf`)
  }
}

export function exportLaTeX(
  stage: Konva.Stage,
  canvasWidth: number,
  canvasHeight: number,
  name: string,
  projectState: ProjectState,
) {
  // Step 1: Export the base image as PNG (with all annotations except text/counters)
  // For simplicity, we export the full stage as PNG
  const dataURL = stageToDataURL(stage, canvasWidth, canvasHeight, 'image/png')

  // Download the PNG
  const pngLink = document.createElement('a')
  pngLink.href = dataURL
  pngLink.download = `${name}.png`
  pngLink.click()

  // Step 2: Generate the .tex file with text annotations as tikz overlays
  const textAnnotations = projectState.annotations.filter((a) => a.type === 'text')
  const counterAnnotations = projectState.annotations.filter((a) => a.type === 'counter')

  let tex = `% Auto-generated by Stift -- Image Annotation & Compositing Tool
% Usage: \\input{${name}.tex}
% Requires: \\usepackage{tikz}, \\usepackage{graphicx}
%
% The base image (${name}.png) contains all graphical annotations.
% Text and counter overlays below use the document's native font.

\\begin{figure}[htbp]
  \\centering
  \\begin{tikzpicture}
    \\node[anchor=south west, inner sep=0] (image) at (0,0)
      {\\includegraphics[width=\\linewidth]{${name}.png}};
    \\begin{scope}[
      x={(image.south east)},
      y={(image.north west)},
    ]
`

  // Add text annotations as tikz nodes (normalized 0-1 coordinates)
  for (const ann of textAnnotations) {
    if (ann.type !== 'text') continue
    const nx = (ann.x / canvasWidth).toFixed(4)
    // tikz y is from bottom, canvas y is from top
    const ny = (1 - ann.y / canvasHeight).toFixed(4)
    const escaped = ann.text
      .replace(/\\/g, '\\textbackslash{}')
      .replace(/[&%$#_{}~^]/g, (m) => `\\${m}`)
    const fontCmd = ann.fontSize <= 10 ? '\\scriptsize'
      : ann.fontSize <= 14 ? '\\footnotesize'
      : ann.fontSize <= 18 ? '\\small'
      : ann.fontSize <= 24 ? '\\normalsize'
      : ann.fontSize <= 30 ? '\\large'
      : '\\Large'
    const style = ann.bold ? '\\bfseries' : ''
    const bg = ann.backgroundColor
      ? ',fill=white,fill opacity=0.85,text opacity=1'
      : ''
    tex += `      \\node[anchor=north west${bg},font={${fontCmd}${style}}] at (${nx},${ny}) {${escaped}};\n`
  }

  // Counter annotations become tikz circle nodes. tikz's color model
  // wants decimal 0-255 components, so we parse the #rrggbb hex out
  // of ann.fill and re-emit it as rgb,255:red,..;green,..;blue,..
  for (const ann of counterAnnotations) {
    if (ann.type !== 'counter') continue
    const nx = (ann.x / canvasWidth).toFixed(4)
    const ny = (1 - ann.y / canvasHeight).toFixed(4)
    const r = parseInt(ann.fill.slice(1, 3), 16)
    const g = parseInt(ann.fill.slice(3, 5), 16)
    const b = parseInt(ann.fill.slice(5, 7), 16)
    tex += `      \\node[circle,fill={rgb,255:red,${r};green,${g};blue,${b}},text=white,font=\\bfseries\\small,inner sep=2pt,minimum size=1.2em] at (${nx},${ny}) {${ann.number}};\n`
  }

  tex += `    \\end{scope}
  \\end{tikzpicture}
  \\caption{${name.replace(/_/g, '\\_')}}
  \\label{fig:${name.replace(/[^a-zA-Z0-9_-]/g, '_')}}
\\end{figure}
`

  // Download the .tex file
  const texBlob = new Blob([tex], { type: 'text/plain' })
  downloadBlob(texBlob, `${name}.tex`)
}
